name: 'Garnet.Standard.Pagination_CICD'

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: pack and push
      uses: Abbas-b-b/Garnet.Github.Actions/dotnet_checkout_pack_push@master
      with:
        project-path: 'src/Garnet.Standard.Pagination/'
        nuget-api-key: ${{ secrets.NUGET_API_KEY }} 
