name: 'Garnet.Detail.Pagination.ListExtensions_CICD'

on:
  push:
    branches:    
    - 'master'
    paths:
    - 'src/Garnet.Detail.Pagination.ListExtensions/**'
    tags:
    - '*.*.*'

jobs:
  pack_push:
    runs-on: ubuntu-latest
    steps:
    - name: Pack and Push
      uses: Abbas-b-b/Garnet.Github.Actions/dotnet_checkout_pack_push@master
      with:
        project-path: 'src/Garnet.Detail.Pagination.ListExtensions/'
        nuget-api-key: ${{ secrets.NUGET_API_KEY }} 
